### ISSUE TITLE
commit updates in `Requests` not visible

### ISSUE THREAD

**Issue by mikkokotila** [Cavai/Sanity#30]
In several projects there is a case like this:

<img width="517" alt="Screenshot 2022-12-05 at 13 27 07" src="https://user-images.githubusercontent.com/7943188/205626266-c772ff08-558b-44d4-ae48-42d5f8756996.png">

...so basically, there is no updates on commits. 

How is this data being generated in the dashboard? Maybe understanding that will help resolve the matter.

**Comment by olszewa** [comment]
@mikkokotila  👋 
Commits are collected from all `opened` Pull Requests including in PR title `RFC`.

**Comment by mikkokotila** [comment]
ah right, nice, thanks :)
